### ISSUE TITLE
Problem Running Notebook

### ISSUE THREAD

**Issue by radetoku** [simpeg-research/miller2018_Tongariro_SP_inversion#1]
from SimPEG.EM.Static import SP appears not available

And couldn't find it on SIMPEG documentation either. Please provide a work around

**Comment by craigmillernz** [comment]
Try running on the SP-spherical branch. @sgkang

**Comment by radetoku** [comment]
Thank you Craig for your reply.
Please where do I find Spherical Branch you referred to. Could you share a link to it? Do I need to make additional installation on my SIMPEG? Please provide detail
